name: Docker Build and Merge

on:
  push: 
    branches:
      - '**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./EmployeeApp
          file: ./EmployeeApp/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/employeeapi:latest

      - name: Auto-merge TestCICD -> master
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch origin master
          git checkout master
          git merge ${GITHUB_REF#refs/heads/} --no-edit
          git push origin master
